add @append command to append items to a list
@append 1 2 3 -i 4 5 6
[1, 2, 3, 4, 5, 6]

✗ @append 1 2 3 -i 4
[1, 2, 3, 4]

@append 1 -i 4
[1, 4]

@append 1 -i
[1, true]

@append 1 -a
ValueError: items parameter required

@append 1 -i 1 2 3
[1, 1, 2, 3]

@append 1
[2, 3, 4]^D
[1, 2, 3, 4]

@echo 1 2 3 | @append 0
[0, 1, 2, 3]

@echo 1 2 3 | @append -i 0
[1, 2, 3, 0]